import { Injectable } from '@angular/core';
import { TopMenu, ImageSliderClass, dataClass, SongClass } from 'src/app/shared/components';

@Injectable()
export class IndexService {
    menus: TopMenu[] = [
        {
          id:1,
          title:'首页',
          link:'index',
          submenus:[
            {
              id:11,
              title:'推荐',
              link:'recommand',
            },
            {
              id:12,
              title:'上新',
              link:'new',
            },
            {
              id:13,
              title:'音乐人',
              link:'musician',
            },
            {
              id:14,
              title:'排行榜',
              link:'rank',
            },
            {
              id:15,
              title:'分区',
              link:'part',
            },
          ]
        },
        {
          id:2,
          title:'音乐',
          link:'music',
          submenus:[
            {
              id:21,
              title:'推荐',
              link:'recommand',
            }
          ]
        },
        {
          id:3,
          title:'动画',
          link:'tv',
          submenus:[
            {
              id:31,
              title:'推荐',
              link:'recommand', 
            }
          ]
        },
        {
          id:4,
          title:'文章',
          link:'articial',
          submenus:[
            {
              id:41,
              title:'推荐',
              link:'recommand',
            }
          ]
        },
        {
          id:5,
          title:'相册',
          link:'photo',
          submenus:[
            {
              id:51,
              title:'推荐',
              link:'recommand',
            }
          ]
        },
        {
          id:6,
          title:'教程',
          link:'teach',
          submenus:[
            {
              id:61,
              title:'推荐',
              link:'recommand',
            }
          ]
        }
    
    ]
    sliders:ImageSliderClass[]=[
       {
        imgUrl:'',
        link:'',
        caption:'',
       } 
    ];
    data:dataClass={
          songNumber:120712,
          upNumber:2012
    };
    newSongs:SongClass[]=[{
        picture:"https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png",
          title:"test",
          author:"茶壶",
          VV:1234
      },{
        picture:"https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png",
          title:"test2",
          author:"茶壶",
          VV:1234
      },{
        picture:"https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png",
          title:"test2",
          author:"茶壶",
          VV:1234
      },{
        picture:"https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png",
          title:"test2",
          author:"茶壶",
          VV:1234
      },{
        picture:"https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png",
          title:"test2",
          author:"茶壶",
          VV:1234
      },{
        picture:"https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png",
          title:"test2",
          author:"茶壶",
          VV:1234
      },{
        picture:"https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png",
          title:"test2",
          author:"茶壶",
          VV:1234
      },{
        picture:"https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png",
          title:"test2",
          author:"茶壶",
          VV:1234
    }];
    getMenus(){
        return this.menus;
    }
    getSliders(){
        return this.sliders;
    }
    getData(){
        return this.data;
    }
    getNewSongs(){
        return this.newSongs;
    }

    
}